USE [master]
GO

/****** Object:  Database [wardrobe]    Script Date: 10/17/2016 9:58:04 PM ******/
CREATE DATABASE [wardrobe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'wardrobe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\wardrobe.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'wardrobe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\wardrobe_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [wardrobe] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [wardrobe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [wardrobe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [wardrobe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [wardrobe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [wardrobe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [wardrobe] SET ARITHABORT OFF 
GO

ALTER DATABASE [wardrobe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [wardrobe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [wardrobe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [wardrobe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [wardrobe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [wardrobe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [wardrobe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [wardrobe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [wardrobe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [wardrobe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [wardrobe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [wardrobe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [wardrobe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [wardrobe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [wardrobe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [wardrobe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [wardrobe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [wardrobe] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [wardrobe] SET  MULTI_USER 
GO

ALTER DATABASE [wardrobe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [wardrobe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [wardrobe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [wardrobe] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [wardrobe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [wardrobe] SET  READ_WRITE 
GO

